name: Set git-user

on: [workflow_call]

jobs:
  lint_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Git-авторизация
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "empty@gmail.com"