name: 'Подготовка окружения Node.js'

# inputs:
#   node-version:
#     description: 'Node.js version'
#     required: false
#     default: '20.x'

runs:
  steps:
    - name: Подгружаем код репозитория
      uses: actions/checkout@v4

    - name: Подгружаем Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20.x

    - name: Подкачиваем npm-зависимости
      run: npm ci