name: Проверка Pull Requests (PR)

on:
  pull_request:
    branches:
      - main
      - 'release/**'
    types:
      - opened     
      - reopened     
      - synchronize  
      - closed      

jobs:
  setup:
    uses: ./.github/workflows/setup.yml

  lint_and_test:
    needs: setup
    uses: ./.github/workflows/lint_and_test.yml

  merge:
    runs-on: ubuntu-latest
    needs: lint_and_test
    steps:
      - name: Мердж изменений
        run: echo "Проверки для pull request прошли успешно, вы можете замержить"

