name: Deploy release to production

on:
  workflow_dispatch:
    branches:
      - 'release/**'
    inputs:
      version:
        description: 'Release version'
        required: true

jobs:
  setup:
    uses: ./.github/workflows/setup.yml
  
  deploy_production:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Подключение к виртуальной машине и загрузка (на неё) Docker-образа из Yandex Registry
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.PUBLIC_IP_VM }}
          port: 22
          username: ${{ secrets.YC_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }} 
          script: |
            echo "${{ secrets.AUTH_REGISTRY_TOKEN }}" | docker login cr.yandex --username oauth --password-stdin
            docker pull cr.yandex/${{ secrets.ID_REGISTRY }}/app:${{ inputs.version }}_latest
            docker stop app || true
            docker rm app || true 
            docker run -d --name app -p 3000:3000 cr.yandex/${{ secrets.ID_REGISTRY }}/app:${{ inputs.version }}_latest

  add_comment_release_issue:
    runs-on: ubuntu-latest
    needs: deploy_production
    steps:
    - name: получить текущую дату
      id: date
      run: echo "date=$(date -u)" >> $GITHUB_ENV

    - name: Add comment to issue
      run: node .github/actions/prod-release-comment.js
      env:
        token: ${{ secrets.ACCESS_TOKEN_GITHUB }}
        date: ${{ env.date }}
        author: ${{ github.actor }}
        version: ${{ inputs.version }}
