name: Анализ кода (eslint) и запуск тестов (jest)

on: [workflow_call]

jobs:
  lint_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Подгружаем код репозитория
        uses: actions/checkout@v4
      
      - name: Подготовка окружения Node.js
        uses: ./.github/workflows/setup.yml

      - name: Запускаем линтер (eslint)
        run: npm run lint
  
      - name: Запускаем тесты (jest)
        run: npm run test