name: Deploy Release to Production

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version'
        required: true

jobs:
  deploy-to-prod:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy Docker image on VM
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.PUBLIC_IP_VM }}
          port: 22
          username: ${{ secrets.YC_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }} 
          script: |
            docker pull cr.yandex/${{ secrets.ID_REGISTRY }}/app:${{ inputs.version }}_latest
            docker stop app || true
            docker rm app || true 
            docker run -d --name app -p 3000:3000 cr.yandex/${{ secrets.ID_REGISTRY }}/app:${{ inputs.version }}_latest

      - name: 
        run: |
          mkdir -p ~/.ssh/
          echo "${{  }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh ${{ secrets.YC_USERNAME }}@${{ secrets.PUBLIC_IP_VM }}
          
      - name: Configure Git
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "default@gmail.com"

      - name: получить текущую дату
        id: date
        run: echo "date=$(date -u)" >> $GITHUB_ENV

      - name: Устанавливаем Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Подкачиваем npm-зависимости
        run: npm ci

      - name: Add comment to issue
        run: node .github/actions/prod-release-comment.js
        env:
          token: ${{ secrets.ACCESS_TOKEN_GITHUB }}
          date: ${{ env.date }}
          author: ${{ github.actor }}
          version: ${{ inputs.version }}
